### ISSUE TITLE
FreePBX extension

### ISSUE THREAD

**Issue by harrymrh** [arnonym/ha-plugins#106]
I have failed to get the add on to register as an extension with freepbx.  Looks like this could be a clue in the logs.

null sound device..
15:14:02.080            pjsua_aud.c  .Opening null sound device..
15:14:02.080           pjsua_core.c  bind() error: Address in use [status=120098]
15:14:02.080           endpoint.cpp  pjsua_transport_create(type, &tcfg, &tid) error: Address in use (status=120098) [../src/pjsua2/endpoint.cpp:2261]
Traceback (most recent call last):
  File "/ha-sip/main.py", line 115, in <module>
    main()
  File "/ha-sip/main.py", line 93, in main
    end_point = sip.create_endpoint(endpoint_config)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ha-sip/sip.py", line 31, in create_endpoint
    end_point.transportCreate(pj.PJSIP_TRANSPORT_UDP, sip_tp_config)
  File "/root/.local/lib/python3.11/site-packages/pjsua2-2.14.1-py3.11-linux-x86_64.egg/pjsua2.py", line 6513, in transportCreate
    return _pjsua2.Endpoint_transportCreate(self, type, cfg)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pjsua2.Error
15:14:02.091           pjsua_core.c  Shutting down, flags=0...

**Comment by arnonym** [comment]
Looks like you already have a SIP client running on the same machine. Do you have the Voice over IP integration enabled? You need to change the port of this one, or ha-sip in the config.

**Comment by harrymrh** [comment]
I changed the port on the VoIP integration that receives incoming calls to recognise voice instructions.  It is a trunk in freepbx.
 It has moved me to a new problem.  While other devices can register this extension from this network homeassistant is getting a 404 error.


10:33:47.356            pjsua_acc.c  ..Acc 0: Registration sent
10:33:47.357           pjsua_core.c  .RX 399 bytes Response msg 404/REGISTER/cseq=9552 (rdata0x7f083dcf8058) from UDP 192.168.4.5:5060:
SIP/2.0 404 Not Found
Via: SIP/2.0/UDP 192.168.5.49:5060;rport=5060;received=192.168.5.49;branch=z9hG4bKPjzVgrugvatpZMQIiVQiCbXc8LdcmMDlnb
Call-ID: XXswifeXVssD4aOTA2oBei4Xqf1sKp6L
From: <sip:350@192.168.4.5>;tag=sBzV0Zd.c-b2sqzsEr7bcS3M1wR4stwL
To: <sip:350@192.168.4.5>;tag=z9hG4bKPjzVgrugvatpZMQIiVQiCbXc8LdcmMDlnb
CSeq: 9552 REGISTER
Server: FPBX-15.0.37.4(16.30.0)
Content-Length:  0


--end msg--
10:33:47.357            pjsua_acc.c  ....SIP registration failed, status=404 (Not Found)

**Comment by arnonym** [comment]
A 404 error is usually the sign of a non-existing user. I never worked with FreePBX but might you need to use a username instead of the extension number?

**Comment by harrymrh** [comment]
FreePBX is a web based gui that sits in front of asterisk.  Asterisk is the pbx behind the scenes.
The user name is the extension.  I have confirmed that it works using other devices to log into the extension from the same network with the same credentials.
Other addons such as DSS VoIP notifier can also not register with the pbx from homeassistant.  I have only been installing one sip addon at a time.

I have just tried disabling the trunk that talks to the VoIP integration for voice recognition in FreePBX.  The extension can now register.
It seems that I need to send calls initiated by homeassistant down the same route as it recieves calls  to the voip integration to keep the PBX happy.

Any ideas on how to have the two coexist happily on the same server?

**Comment by NODeeJay** [comment]
I was wondering the last 2 hours why the heck I do not get a simple extension from FreePBX with ha-sip running. I encounter exactly the issue as described, and I have also HA Assist in the trunk option in FreePBX.

To reproduce:
1. have a **trunk** in FreePBX with HA as SIP server to connect to HA Assist
2. have an **outbound route** to catch a dediated number to call HA Assist
3. add an extension that should be used by ha-sip

@harrymrh to confirm please try to remove the trunk from the outbound route that connects HA Assist and try to login again from ha-sip. As soon as I removed the trunk from the route it worked, just disabling the trunk did not help, the route seemed the issue.

As soon as the trunk is active and the route configured Asterisk (System Log) logs after REGISTER a `SIP/2.0 404 Not Found` and throws a warning `2024-11-04 22:10:21] WARNING[35453] res_pjsip_registrar.c: AOR '' not found for endpoint 'HAAssist' (192.168.**.**:5061)`
Since only the trunk is called this way I startet my investigation disabling it and the routing. The problem is IMHO caused by FreePBX/Asterisk and not the addon at all, since it seems the exentsion registers fine, as long as there is no trunk configured for the IP address the extension comes from. 

I started searching for this specific FreePBX issue: https://community.freepbx.org/t/pjsip-fails-when-extension-and-trunk-s-are-both-at-same-local-ip-address-as-from-obihai-device/62676

The main problem is our `/etc/asterisk/pjsip.identify.conf` and the entry for the match
```
[HAAssist]
type=identify
endpoint=HAAssist
match=192.168.***.***
```

I read a lot about custom config files to overwrite the match entry and found one article that described the options: https://community.freepbx.org/t/pjsip-endpoint-matching/54167/10. While mostly self explaining I did not find one from that list for the trunk that worked. It looked like I have to delve into Asterisk and configure this endpoint by hand....
But it was already late, I was annoyed and tried the shortcut to enter the IP and the port in the Match (Permit) for the trunk and for the extension, restarted Asterisk and the trunk connected. I now have some issue with Assist, not sure if it came from that change. I will continue the next days and maybe I find the winning combination of matches.

**Comment by glvanlier** [comment]
I previously had my extension on FreePBX working with HA-SIP. However, after an upgrade from my server and with it an upgrade of FreePBX to the latest version, chan_sip is no longer supported by Asterisk. Only PJSIP. Since then, I can not get my extension registered on Home Assistant. Can anyone confirm this? Or has anyone found a way, even with another addon/integration in Home Assistant, to make it work?

**Comment by NODeeJay** [comment]
@glvanlier this is basically what [this article](https://community.freepbx.org/t/pjsip-fails-when-extension-and-trunk-s-are-both-at-same-local-ip-address-as-from-obihai-device/62676) refers to. However, the main question is: do you also use Assist with the trunk in FreePBX AND the extension pointing to the same IP of HomeAssistant?

My trunk to use Assist is configured with HA as the `SIP Server` and _5060_ as `SIP Server Port`. `Authentication` and `Registration` is both set to _none_. `Codec` is set to _opus_ only and under pjsip Setings `Match Permit` points to the _HA-IP:5060_.
In the `Outbound Routes` I just configured the `Dial Patterns` with a `Match Pattern` (since no number needs to be dialed) and the I also added "`Intercompany`" to have a bit visual differencies. 

The extension is configured under `Advanced` as well with `Match Pattern` but with _HA-IP:5061_, which corresponds to the port of the addon. I tried with _username_ in first instance which did not work.

In ha-sip I have the extension configured like:
_global_
```
port: 5061
log_level: 5
name_server: ""
cache_dir: ""
```
_sip_
```
enabled: true
registrar_uri: sip:sip.**.**
id_uri: sip:232@sip.**.**
realm: "*"
user_name: "232"
password: password
answer_mode: listen
settle_time: 1
incoming_call_file: ""
```
Intermittent it connected, so I updated FreePBX to version 17.0.19.16 (before was on a 17.0.19.11), however, the main problem was, which caused several extensions not being correctly reachable by Home Assistant or that ha-sip did not register from time to time, that somehow the config files were not good. In this [thread](https://community.freepbx.org/t/after-move-upgrade-all-calls-to-extensions-go-to-unavailable-voicemail/70764) I found the command to reset Asterisk DB/recerate all configurations from FreePBX `fwconsole util resetastdb`. As soon as I did it everything started working perfectly. Assist can be used from all phones, ha-sip is registered and can receive and make phone calls.

Do you mind giving it a try following my config above?

**Comment by NODeeJay** [comment]
@harrymrh I was meanwhile able to replicated successful connection with another FreePBX and current HA + ha-sip. Please check my settings above if it fixes the issue also for you, then I think we can close this ticket.

**Comment by glvanlier** [comment]
@NODeeJay , thanks for your reply.

I am not quite sure if I understand. Are you also running Asterisk on Home Assistant? As you say 
> My trunk to use Assist is configured with HA as the `SIP Server` and _5060_ as `SIP Server Port`.

Or did you create a seperate trunk on FreePBX just for HA?

With this you mean Advanced on the extension in FreePBX? What settings should be set here?
> The extension is configured under `Advanced` as well with `Match Pattern` but with _HA-IP:5061_, which corresponds to the port of the addon. I tried with _username_ in first instance which did not work.

There are also IP phones in the house that are connected to FreePBX for inbound and outbound calls. Port 5060 is used for communication with the internet (provider) and port 5061 for the IP phones.

At this point, I only want to be able to connect HA to the PBX using PJSIP. This so I can call my doorbell and use it in automations. Later on, I would like to add Assist.

With these settings:
```
enabled: true
registrar_uri: sip:sip.**.**
id_uri: sip:232@sip.**.**
realm: "*"
user_name: "232"
password: password
answer_mode: listen
settle_time: 1
incoming_call_file: ""
```

Should I add my IP-address on the ** or exactly like this, only changing the extension and password?

**Comment by NODeeJay** [comment]
> I am not quite sure if I understand. Are you also running Asterisk on Home Assistant? As you say
> Or did you create a seperate trunk on FreePBX just for HA?

I am running HA and FreePBX on different devices, which in the end does not matter much, since in OP's and my config the "special" case is that we use _Home Assistant Assist_ with a _trunk_ in FreePBX **and additionally** want to register an _extension_ with **ha-sip** on the same FreePBX. Your case might be a bit different, if so, you are better of opening a new issue.
 
### Trunk for Assist
#### General
![image](https://github.com/user-attachments/assets/c7e88b99-2486-4876-a2f4-28eb88c2d555)
`HA-IP:5060`
#### pjsip settings / Advanced
![image](https://github.com/user-attachments/assets/7a3ed2dc-1dc6-4569-9f0c-0d2f10739328)
`HA-IP:5060`

#### Outbound route for the Trunk
Route Settings: the trunk configured above
Dial Patterns: match pattern (the internal number you want to use for Assist)


> With this you mean Advanced on the extension in FreePBX? What settings should be set here?
> 
> > The extension is configured under `Advanced` as well with `Match (Permit)` but with _HA-IP:5061_, which corresponds to the port of the addon. I tried with _username_ in first instance which did not work.

### Extension for ha-sip
Configure it as usual, maybe no VM and no Follow Me
#### Advanced
![image](https://github.com/user-attachments/assets/75d7422e-d906-4888-b1b2-86392d2e56b7)
`HA-IP:5061`


> At this point, I only want to be able to connect HA to the PBX using PJSIP. This so I can call my doorbell and use it in automations. Later on, I would like to add Assist.

Follow the config above for the extension. To be ready for the Assist function use `Match (Permit)` on the extension already.

> With these settings:
> 
> ```
> enabled: true
> registrar_uri: sip:sip.**.**
> id_uri: sip:232@sip.**.**
> realm: "*"
> user_name: "232"
> password: password
> [...]
> ```
> 
> Should I add my IP-address on the ** or exactly like this, only changing the extension and password?

Well, IP or if you use FQDNs of your PBX
`registrar_uri: sip:192.168.0.1` or
`registrar_uri: sip:sip.yourdnsname.org`
id_uri follows the same rule plus the extension (same as user_name)

Additionally, under global
`port: 5061`

To find out if you have an issue with the match (see my [comment](https://github.com/arnonym/ha-plugins/issues/106#issuecomment-2455869662) above) check the asterisk log for `WARNING[35453] res_pjsip_registrar.c: AOR '' not found for endpoint 'HAAssist' (192.168.**.**:5061)`

**Comment by glvanlier** [comment]
@NODeeJay, thank you for the detailed instructions. Very much appreciated. Unfortunately it is still not working.

HA-SIP global:
```
port: 5061
log_level: 5
name_server: ""
cache_dir: ""
```

HA-SIP sip:
```
enabled: true
registrar_uri: sip:192.168.178.100
id_uri: sip:301@192.168.178.100
realm: "*"
user_name: "301"
password: xxxxxx
answer_mode: listen
settle_time: 1
incoming_call_file: ""
```

All other settings for FreePBX regarding the Trunk, inbound and extension as per your instructions:
![afbeelding](https://github.com/user-attachments/assets/f5d5f00a-e0be-4df4-bdcc-9d64c7b9527e)

![afbeelding](https://github.com/user-attachments/assets/1dd2049a-335e-4a34-8747-5224763a6bd3)
`Trunk advanced`

![afbeelding](https://github.com/user-attachments/assets/88c5568d-b9f6-4254-9e70-03900c375138)
`Extension advanced`

The following is in Reports > Asterisk Info:
![afbeelding](https://github.com/user-attachments/assets/b1a19c83-ee52-4d53-bc34-c25250777528)

The log files of Asterisk in FreePBX don't show anything regarding this extension being registered.

HA-SIP log:
```
16:12:09.478            pjsua_acc.c  ...SIP registration failed, status=408 (Request Timeout)
16:12:09.478            pjsua_acc.c  ...Scheduling re-registration retry for acc 0 in 292 seconds..
| 16:12:09.478387 [1] OnRegState: 408 Request Timeout
```

Any hints on why it is not working?

**Comment by NODeeJay** [comment]
So often I found myself stuck with an IT issue and people wrote in a forum with exactly the issue I had: "I found the solution, thanks for all your help" and closed the issue and I sit in front of the screen like "Where solution?" - you know the meme with the three monkeys :-)

In _Asterisk Info_ a connected and registered extension for HA looks like this
```
Endpoint:  232/232                                              Not in use    0 of inf
InAuth:  232-auth/232
Aor:  232                                                1
Contact:  232/sip:232@192.168.*.*:5061;ob         cd3601c3cf Avail         2.031
Identify:  232-identify/232
Match: 192.168.*.*:5061/32
```
Note, the contact is `Avail` and on top of that page you should see the the extension under `Channels` in green.

Does your trunk work with HA Assist? Can you dial, does Assist pick up or do you hear the initial Assist announcement to activate Assist/VoIP in HA?

`408` is different, your HA seems no to be able to connect to the PBX and times out. If you can ping but not register and there is nothing in _Asterisk / System Logs_ visible when you restart **ha-sip**, I bet fail2ban and the firewall in FreePBX blocked the IP (which FreePBX does for extensions but not for trunks!), check _Connectivity / Firewall / Intrusion detection_ and maybe exclude your internal range(s).

If you don't find it there the ususal IT needle in a haystack starts:
1. try to ping FPBX from HA (HA command line, portainer and from some container's console, ping sensor, etc.) and vice versa.
2. check firewall on OS level of FPBX
3. try to register the same extension from a softphone, e.g. Linphone, Zoiper, 3CX - this will also show you how it should look like in the _Asterisk Info_ and the _System Log_
4. check with `sudo sngrep -l 20 -R` on FPBX while you register the extension if you see the _SIP Method_ `REGISTER`
5. recreate all Asterisk config files with `sudo fwconsole util resetastdb` on FPBX (no harm if you don't have self hacked config files that you manually changed on the console instead of using the "custom" config files in FPBX)
6. If you have the equipment: port mirror the HA and the FPBX port, connect 2 PCs or a PC with 2 network adapters and Wireshark both mirrored ports

Thumbs pressed 👍

**Comment by NODeeJay** [comment]
Yep, extensions and trunk both on pjsip. Earlier you wrote that the _Asterisk System Logs_ does not show anything when you try to register from **ha-sip** and **ha-sip** then times out.
Do you have the chance to try **ha-sip** against a different PBX/provider or did you register maybe with sip2 or sip3 succesfully?

When you can ping from HA but the packages from **ha-sip** to register do not arrive at FPBX it might be an issue with access from the ha-sip container/addon. If you have the portainer addon, can you try to ping from the **ha-sip** container? There might be also an option on the command line, but I only know it with portainer.

**Comment by glvanlier** [comment]
@NODeeJay 

I unfortunately cannot try another provider. The provider that is in the trunk on FreePBX is working, but since the provider is not easy when it comes to wrong registrations, I don't dare to try.

I also tried using sip 2 and sip 3, but same results.

I am running Home Assistant OS in a Proxmox VM. HA-SIP runs as an addon. I guess then that pinging from the HA-SIP container is not doable?

The thing is, when on my previous installation I tried to use PJSIP, I also could not get it to work. I then changed the extension in FreePBX to just SIP, and it worked. So that was why I thought it had someting to do with SIP vs PJSIP. But you have it working, so that should not matter.

**Comment by engineer88-gorinchem** [comment]
I recently got it working. ChatGPT helped me with that.

My config is now as follows:
**SIP_GLOBAL**
`port: 5061
log_level: 5
name_server: ""
cache_dir: ""`

**SIP**
`enabled: true
registrar_uri: sip:192.168.178.100:5061
id_uri: sip:301@192.168.178.100:5061
realm: "*"
user_name: "301"
password: 57bf006e27eb623907d352fa1edbcf75
answer_mode: listen
settle_time: 1
incoming_call_file: ""`

In the end it was only a matter of adding port 5061 to the IP. Somehow HA-SIP was adding 5060, despite configuring port 5061 in the global sip settings. Maybe something to change in a next relase?

**Comment by arnonym** [comment]
The port in the global settings is the port ha-sip is listening on. The port in the registrar_uri is the port the SIP server you're connecting to is listening on. There's nothing ha-sip can do here. But glad you figured it out! 🚀
